### ISSUE TITLE
Comilla perdida en ejemplo de gen_admin_div()

### ISSUE THREAD

**Issue by brianmsm** [healthinnovation/innovar#58]
En el ejemplo, AYACUCHO no se encuentra entre comillas, y produce que todo el ejemplo se ejecute con error:
https://github.com/healthinnovation/innovar/blob/a45982942a7814641d78a988bb65a0b8ac6e2bc0/R/gen_admin_div.R#L24

**Comment by ambarja** [comment]
Gracias @brianmsm por la observación, esto ya fue corregido :rocket:
